name: build the application

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup repo
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ">=18.x"
          cache: npm

      - name: setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPOI18N_TOKEN }}

      - name: install dependencies
        run: npm install

      - name: build for android
        run: eas build --platform android --profile preview --non-interactive

      - name: build for ios
        run: eas build --platform ios --profile preview --non-interactive
